queue_rules:
  - name: default
    queue_conditions:
      - "check-success=build"
    merge_conditions:
      - "check-success=build"
    update_method: rebase

pull_request_rules:
  - name: queue_renovate_pr
    conditions:
      - "author=renovate[bot]"
      - "check-success=build"
    actions:
      queue:
        merge_method: merge
  - name: delete_merged_pr
    conditions:
      - merged
    actions:
      delete_head_branch: {}
