queue_rules:
  - name: default
    queue_conditions:
      - "check-success=build"
      - "author=renovate[bot]"
    merge_conditions:
      - "check-success=build"
    update_method: rebase

    merge_method: merge

pull_request_rules:
  - name: delete_merged_pr
    conditions:
      - merged
    actions:
      delete_head_branch: {}
  - name: queue_renovate_pr
    conditions: []
    actions:
      queue:
